{
 "title": "Open5GS",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "AMF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAN UEs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ran_ue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "amf_session", "legendFormat": "__auto" }
   ]
  },
  { "title": "SMF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active UEs",
   "type": "timeseries",
   "description": "Active User Equipments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ues_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active SMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UPF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active UPF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}