services:
  gnb:
    extends:
      file: ${DOCKER}/srsran/project/services.yaml
      service: gnb
    environment:
      - RF_DEVICE_NAME=uhd
      - RF_DEVICE_ARGS=type=b200,num_recv_frames=64,num_send_frames=64

  mysql:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: mysql

  nrf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: nrf

  amf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: amf

  smf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: smf

  upf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: upf

  udr:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: udr

  udm:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: udm

  ausf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: ausf
