services:
  gnb:
    extends:
      file: ${DOCKER}/srsran/project/services.yaml
      service: gnb
    environment:
      - RF_DEVICE_NAME=uhd
      - RF_DEVICE_ARGS=type=b200,num_recv_frames=64,num_send_frames=64

  mysql:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: mysql

  nrf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: nrf

  amf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: amf
    depends_on: [ ausf, mysql, nrf ]

  smf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: smf
    depends_on: [ amf, nrf ]

  upf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: upf
    depends_on: [ nrf ]

  udr:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: udr
    depends_on: [ mysql, nrf ]

  udm:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: udm
    depends_on: [ udr ]

  ausf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: ausf
    depends_on: [ udm ]
