services:
  mysql:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: mysql

  amf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: amf
    volumes:
      - ./cn5g.yaml:/mnt/oai/cn5g.yaml:ro
    depends_on: !override
      mysql:
        condition: service_healthy

  smf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: smf
    volumes:
      - ./cn5g.yaml:/mnt/oai/cn5g.yaml:ro
    depends_on: !override
      amf:
        condition: service_healthy

  upf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: upf
    volumes:
      - ./cn5g.yaml:/mnt/oai/cn5g.yaml:ro
    depends_on: !override []

  gnb:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: gnb

  ue:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: ue

  o5gc-dns:
    image: cytopia/bind:stable-0.28
    container_name: o5gc-dns
    privileged: true
    environment:
      # Custom DNS entries:
      # - bild.de -> tagesschau.de
      - DNS_A=bild.de=88.215.213.26
      - DNS_FORWARDER=8.8.8.8,8.8.4.4
      - DEBUG_ENTRYPOINT=2
      - DOCKER_LOGS=1
    networks:
      extnet:
        ipv4_address: ${DNS_EXT_IP_ADDR}
    profiles: [ "core" ]
