run-stack1_correct_makefile:
	echo STARTED > ./stack1_correct_makefile_started
	echo ${ENV_OVERRIDES_PATH} > ./stack1_env_overrides_path
stop-stack1_correct_makefile:
	echo STOPPED > ./stack1_correct_makefile_stopped

run-stack3_stop_fails:
	exit 0

stop-stack3_stop_fails:
	exit 42
