services:
  base:
    extends:
      file: ${MODULES}/base/docker/o5gc/services.yaml
      service: base-ran
    image: o5gc/ocudu
    entrypoint: [ "/mnt/ocudu/entrypoint.sh" ]
    volumes:
      - .:/mnt/ocudu/:ro
      - ${DEVELOP_VOLUME_OCUDU:-${BASE}/var/empty:/var/empty}
    profiles: [ ocudu ]
  gnb:
    extends:
      service: base
    container_name: gnb
    command: gnb
    environment:
      - DOCKER_TARGET_HOSTNAME=${GNB_HOSTNAME}
    networks:
      rfnet:
        ipv4_address: ${GNB_RF_IP_ADDR}
      corenet:
        ipv4_address: ${GNB_IP_ADDR}
    profiles: [ "gnb" ]
  cu:
    extends:
      service: base
    container_name: cu
    command: cu
    environment:
      - DOCKER_TARGET_HOSTNAME=${GNB_HOSTNAME}
    networks:
      corenet:
        ipv4_address: ${CU_CP_CORENET_IP_ADDR}
      f1net:
        ipv4_address: ${CU_CP_IP_ADDR}
    profiles: [ "cu" ]
  cu-cp:
    extends:
      service: base
    container_name: cu-cp
    command: cu-cp
    environment:
      - DOCKER_TARGET_HOSTNAME=${GNB_HOSTNAME}
    networks:
      corenet:
        ipv4_address: ${CU_CP_CORENET_IP_ADDR}
      f1net:
        ipv4_address: ${CU_CP_IP_ADDR}
    profiles: [ "cu-cp" ]
  cu-up:
    extends:
      service: base
    container_name: cu-up
    command: cu-up
    networks:
      corenet:
        ipv4_address: ${CU_UP_CORENET_IP_ADDR}
      f1net:
        ipv4_address: ${CU_UP_IP_ADDR}
    profiles: [ "cu-up" ]
  du:
    extends:
      service: base
    container_name: du
    command: du
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    environment:
      - DOCKER_TARGET_HOSTNAME=${GNB_HOSTNAME}
    networks:
      rfnet:
        ipv4_address: ${GNB_RF_IP_ADDR}
      f1net:
        ipv4_address: ${DU_IP_ADDR}
    profiles: [ "du" ]
