services:
  epc:
    extends:
      file: ${DOCKER}/srsran/4g/services.yaml
      service: epc

  enb:
    extends:
      file: ${DOCKER}/srsran/4g/services.yaml
      service: enb
    depends_on: [ epc ]
    environment:
      - RF_DEVICE_NAME=zmq
      - RF_DEVICE_ARGS=fail_on_disconnect=true,tx_port=tcp://${ENB_RF_IP_ADDR}:2000,rx_port=tcp://${UE_RF_IP_ADDR}:2001,id=enb,base_srate=23.04e6

  ue:
    extends:
      file: ${DOCKER}/srsran/4g/services.yaml
      service: ue
    depends_on: [ enb ]
    environment:
      - RF_DEVICE_NAME=zmq
      - RF_DEVICE_ARGS=tx_port=tcp://${UE_RF_IP_ADDR}:2001,rx_port=tcp://${ENB_RF_IP_ADDR}:2000,id=ue,base_srate=23.04e6"
      - TX_GAIN=80
      - RX_GAIN=40
      - USIM_MODE=soft
      - USIM_ALGO=mil
      - USIM_OPC=${UE_SOFT_OPC}
      - USIM_KEY=${UE_SOFT_KEY}
      - USIM_IMSI=${MCC}${MNC}${UE_SOFT_MSIN}
      - USIM_IMEI=353490069873319
      - EUTRA_NOF_CARRIERS=1
      - UE_RELEASE=14
