# Provision Carrier Privileges

set echo true
set debug true

select ADF.ARA-M
aram_delete_all

# OMNT (Open Mobile Network Toolkit)
aram_store_ref_ar_do --aid ffffffffffff --device-app-id E849B63A7B96E571F788FC5845C4AA3C520D18E8 --android-permissions 0000000000000001

# CoIMS (Carrier Config overriding IMS settings)
aram_store_ref_ar_do --aid ffffffffffff --device-app-id E46872F28B350B7E1F140DE535C2A8D5804F0BE3 --apdu-always --android-permissions 0000000000000001
