services:
  mysql:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: mysql

  nrf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: nrf

  amf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: amf

  smf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: smf

  upf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: upf

  udr:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: udr

  udm:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: udm

  ausf:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: ausf

  gnb:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: gnb
    image: o5gc/oai-ran:2024.w23-4.4.0.0
    command: gnb --sa
    volumes:
      - ./gnb.conf:/o5gc/openairinterface5g/etc/gnb.conf:ro

  ue:
    extends:
      file: ${DOCKER}/oai/services.yaml
      service: ue
    image: o5gc/oai-ran:2024.w23-4.4.0.0
    command: nr-ue -r 106 --numerology 1 --band ${NR_BAND} -C $(scripts/band_helper.py arfcn_to_freq ${NR_ARFCN})
    environment:
      - OAI_RFSIM_SERVERADDR=${GNB_RF_IP_ADDR}
    volumes:
      - ./ue.conf:/o5gc/openairinterface5g/etc/nr-ue.conf:ro

  o5gc-dns:
    image: cytopia/bind:stable-0.28
    container_name: o5gc-dns
    privileged: true
    environment:
      # Custom DNS entries:
      # - bild.de -> tagesschau.de
      - DNS_A=bild.de=88.215.213.26
      - DNS_FORWARDER=8.8.8.8,8.8.4.4
      - DEBUG_ENTRYPOINT=2
      - DOCKER_LOGS=1
    networks:
      extnet:
        ipv4_address: ${DNS_EXT_IP_ADDR}
    profiles: [ "core" ]
