services:
  coredns:
    image: coredns/coredns:1.11.3
    container_name: coredns
    volumes:
      - ./coredns.cfg:/home/nonroot/Corefile:ro
    networks:
      - corenet
    profiles: [ "coredns" ]
